name: e2e

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      # Define the rules that need to trigger the workflow
      - "**/*.py"
      # Recipes
      - "!recipe/verl_use_case"
      # Entrypoints
      - ".github/workflows/e2e.yml"

# Cancel jobs on the same ref if a new one is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

# Declare permissions just read content.
permissions:
  contents: read

jobs:
  e2e:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 20 # Increase this timeout value as needed
    strategy:
      matrix:
        python-verison: ["3.10"]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install PyTorch
        run: |
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
      - name: Install the current repository
        run: |
          pip3 install -e .
      - name: Running simple use case E2E tests
        run: |
          ray stop --force
          python3 recipe/simple_use_case/start_transferqueue.py
